<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyName>HomelanderNPC</AssemblyName>
    <RootNamespace>HomelanderNPC</RootNamespace>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>

    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>

    <!-- MelonLoader -->
    <PackageReference
      Include="LavaGang.MelonLoader"
      Version="0.6.5" />

    <!-- Unity -->
    <PackageReference
      Include="UnityEngine.CoreModule"
      Version="2020.3.1" />

  </ItemGroup>

</Project>
